carts/templates/carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'),
    path('cart_change/<slug:product_slug>/', views.cart_change, name='cart_change'),
    path('cart_remove/<slug:product_slug>/', views.cart_remove, name='cart_remove'),
]

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('woman/', views.catalogWoman, name='catalog-woman'),
    path('woman/<slug:category_slug>/', views.catalogWoman, name='catalog-woman-category'),
    path('men/', views.catalogMen, name='catalog-men'),
    path('men/<slug:category_slug>/', views.catalogMen, name='catalog-men-category'),
    path('product/', views.product, name='product'),
    path('product/<int:product_id>', views.product, name='product'),
]

ignis_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from ignis_app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('catalog/', include('goods.urls', namespace = 'catalog-men')),
    path('catalog/', include('goods.urls', namespace = 'catalog-woman')),
    path('user/', include('users.urls', namespace = 'user')),
    path('cart/', include('carts.urls', namespace = 'cart')),
]

if settings.DEBUG:
    # urlpatterns = [
    #     path("__debug__/", include("debug_toolbar.urls")),
    # ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('', views.logout, name='logout'),
]

carts/models.py
from django.db import models
from users.models import User
from goods.models import Products

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    class Meta:
        db_table = 'cart'
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'
    
    def __str__(self):
        return f'Корзина пользователя {self.user.username}'

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items', verbose_name='Корзина')
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
    
    class Meta:
        db_table = 'cart_item'
        verbose_name = 'Элемент корзины'
        verbose_name_plural = 'Элементы корзины'
    
    def __str__(self):
        return f'{self.product.name} - {self.quantity} шт.'

carts/forms.py
from django import forms
from .models import CartItem

class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ['quantity']

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User

class UserLoginForm(AuthenticationForm):
    pass
    class Meta:
        model = User
        fields = ['username', 'password',]


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "username",
            "phone_number",
            "password1",
            "password2",
        )
    
    username = forms.CharField()
    phone_number = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
            "town",
            "street",
            "house",)

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    phone_number = forms.CharField()
    town = forms.CharField()
    street = forms.CharField()
    house = forms.CharField()

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from goods.models import Products
from .models import Cart, CartItem

@login_required
def cart_detail(request):
    cart, created = Cart.objects.get_or_create(user=request.user)
    context = {
        'title': 'IGNIS - Корзина',
        'cart': cart
    }
    return render(request, 'carts/carts.html', context)

@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Products, id=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    if not created:
        cart_item.quantity += 1
    cart_item.save()
    return redirect('carts:cart_detail')

@login_required
def remove_from_cart(request, product_id):
    cart = get_object_or_404(Cart, user=request.user)
    cart_item = get_object_or_404(CartItem, cart=cart, product_id=product_id)
    cart_item.delete()
    return redirect('carts:cart_detail')

carts/templates/carts/carts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static "deps/css/style.css" %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static "deps/css/normalize.css" %}">
        <link rel="icon" href="{% static "deps/media/favicon.ico" %}"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{ title }}</title>
    </head>
<body>
    <header class="header">
        <div class="container">
            <div class="header-flex">
                <nav class="header-menu-left">
                    <ul class="header-menu-list">
                        <li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-woman" %}"><i class="fa-solid fa-venus"></i> Женщинам</a></li>
                        <li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-men" %}"><i class="fa-solid fa-mars"></i> Мужчинам</a></li>
                    </ul>
                </nav>
                <div class="header-logo">
                    <a href="{% url "main:index" %}"><img src="{% static "deps/media/main/header/Logo.svg" %}" alt="" class="header-avatar"></a>
                    <div class="header-line">
                        <img src="{% static "deps/media/main/header/Line 1.svg" %}" alt="">
                    </div>
                    <h1 class="header-title">
                        <a class="header-title-link" href="{% url "main:index" %}">ignis</a>
                    </h1>
                </div>
                <nav class="header-menu-right">
                    <ul class="header-menu-list">
                        {% if not user.is_authenticated %}
                            <li class="header-menu-item"><a class="header-menu-link" href="{% url "users:login" %}"><i class="fa-solid fa-right-to-bracket"></i> Войти</a></li>
                        {% else %}
                            <li class="header-menu-item"><a class="header-menu-link" href="{% url "users:profile" %}"><i class="fa-solid fa-user"></i> Профиль</a></li>
                            <li class="header-menu-item"><a class="header-menu-link" href="favorites.html"><i class="fa-solid fa-heart"></i> Избранное</a></li>
                            <li class="header-menu-item"><a class="header-menu-link" href="{% url "cart:cart_detail" %}"><i class="fa-solid fa-cart-shopping"></i> корзина</a></li>
                            {% if user.is_admin or user.is_staff%}
                            <li class="header-menu-item"><a class="header-menu-link" href="{% url "admin:index" %}"><i class="fa-solid"></i> админ панель</a></li>
                            {% endif %}
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <main>
        <section class="cart">
            <div class="container">
                <nav class="cart-navbar">
                    <ul class="cart-list">
                        <li class="cart-item"><a href="{% url 'main:index' %}" class="cart-link">Главная</a></li>
                        <i class="fa-solid fa-chevron-right"></i>
                        <li class="cart-item"><a href="{% url 'cart:cart_detail' %}" class="cart-link">Корзина</a></li>
                    </ul>
                </nav>
                <h1 class="cart-title">
                    <a href="{% url 'cart:cart_detail' %}">Ваш заказ</a>
                </h1>
                {% for item in cart.items.all %}
                <div class="cart-info">
                    <div class="cart-img-name">
                        <img src="{{ item.product.image.url }}" alt="" class="cart-avatar">
                        <p class="cart-name">{{ item.product.name }}</p>
                    </div>
                    <p class="cart-vendor">арт. {{ item.product.id }}</p>
                    <div class="cart-color">
                        <img src="{% static 'deps/media/cart/color_'|add:item.product.color|add:'.svg' %}" alt="" class="cart-img-color">
                    </div>
                    <div class="cart-minus-plus">
                        <a href="{% url 'carts:remove_from_cart' item.product.id %}"><i class="fa-solid fa-minus"></i></a>
                        <p class="cart-num">{{ item.quantity }}</p>
                        <a href="{% url 'carts:add_to_cart' item.product.id %}"><i class="fa-solid fa-plus"></i></a>
                    </div>
                    <p class="cart-num">
                        {{ item.product.price|floatformat:2 }} руб.
                    </p>
                    <a href="{% url 'carts:remove_item' item.product.id %}"><img src="{% static 'media/cart/cart.svg' %}" alt="" class="cart-images"></a>
                </div>
                {% endfor %}
                <p class="cart-price">
                    К оплате: <span class="cart--fw-bold">{{ cart.get_total_price|floatformat:2 }} руб</span>
                </p>
                <p class="cart-decor">
                    Оформление заказа
                </p>
                <div class="cart-flex">
                    <div class="cart-data">
                        <p class="cart-data-text">
                            Персональные данные:
                        </p>
                        <form action="{% url 'user:profile' %}" method="post" class="cart-form">
                            {% csrf_token %}
                            <div class="cart-item">    
                                <input type="text" id="id_first_name" name="first_name" value="{{ form.first_name.value|default_if_none:'' }}" placeholder="Ваше имя*" required>
                                <input type="text" id="id_last_name" name="last_name" value="{{ form.last_name.value|default_if_none:'' }}" placeholder="Ваша фамилия*">
                            </div>
                            <div class="cart-item">    
                                <input type="email" id="id_email" name="email" value="{{ form.email.value|default_if_none:'' }}" placeholder="Ваш e-mail*" required>
                                <input type="phone" id="id_phone_number" name="phone_number" value="{{ form.phone_number.value|default_if_none:'' }}" placeholder="Ваш номер телефона*" required>
                            </div>
                            <p class="cart-data-text">
                                Способ доставки:
                            </p>
                            <p class="cart-data-text">
                                По России:
                            </p>
                            <div class="cart-delivery">
                                <div class="cart-cash">
                                    <input type="radio" name="delivery" value="pickup" id="pickup" checked>
                                    <label for="pickup" class="cart-huy">Самовывоз - {{ form.town.value }}</label>
                                </div>
                                <div class="cart-cash">
                                    <input type="radio" name="delivery" value="nova_poshta" id="nova_poshta">
                                    <label for="nova_poshta" class="cart-huy">Почта России</label>
                                </div>
                            </div>
                            <p class="cart-data-text">
                                Адрес доставки:
                            </p>
                            <div class="cart-item">    
                                <input type="text" name="city" placeholder="Город*" required>
                                <input type="text" name="post_office" placeholder="Отделение почты*">
                            </div>
                            <p class="cart-data-text">
                                Вы можете оплатить покупку одним из ниже перечисленных способов:
                            </p>
                            <div class="cart-delivery">
                                <div class="cart-cash">
                                    <input type="radio" name="payment" value="transfer" id="transfer" checked>
                                    <label for="transfer" class="cart-huy">Денежным переводом</label>
                                    <img src="{% static 'deps/media/cart/Combined-Shape.svg' %}" alt="" class="cart-mir">
                                </div>
                                <div class="cart-cash">
                                    <input type="radio" name="payment" value="cash_on_delivery" id="cash_on_delivery">
                                    <label for="cash_on_delivery" class="cart-huy">Наложенным платежом в отделении Почты России</label>
                                </div>
                            </div>
                            <div class="cart-offer">
                                <p class="cart-offer-text">
                                    ДОСТАВКА: <span class="cart-offer-text--fw-bold">По тарифам перевозчика</span> 
                                </p>
                                <p class="cart-offer-text">
                                    ИТОГО: <span class="cart-offer--text-right">{{ cart.get_total_price|floatformat:2 }} руб</span> 
                                </p>
                                <button type="submit" class="cart-offer-button">
                                    ОФОРМИТЬ ЗАКАЗ
                                </button>
                                <p class="cart-offer-text-under">
                                    Нажимая на кнопку «оформить заказ», я <br> принимаю условия публичной оферты и <br> политики конфиденциальности
                                </p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer class="footer">
        <div class="container">
            <div class="footer-flex">
                <div class="footer-number">
                    <a href="">
                        <i class="fa-solid fa-phone fa-2xl"></i>
                        <p class="footer-text">
                            +7 (999) 999 99-99
                        </p>
                    </a>
                </div>
                <div class="footer-adress">
                    <a href=""><i class="fa-solid fa-location-dot fa-2xl"></i></a>
                    <p class="footer-text">
                        <a class="footer-map" href="https://maps.app.goo.gl/uRuEgu8wuG3qbstY8">г. Брянск, пр-т Станке Димитрова, д. 3 </a>
                    </p>
                </div>
                <div class="footer-mail">
                    <a href=""><i class="fa-solid fa-envelope fa-2xl"></i></a>
                    <p class="footer-text">
                        <a href="">ignis@gmail.com</a>
                    </p>
                </div>
                <div class="footer-schedule">
                    <i class="fa-solid fa-calendar fa-2xl"></i>
                    <p class="footer-text">
                        с 08:00 <br> до 22:00 по МСК
                    </p>
                </div>
                <div class="footer-social">
                    <a class="footer-link-social" href=""><i class="fa-brands fa-telegram fa-2xl"></i></a>
                    <a class="footer-link-social" href="https://vk.com/bgitu_ru"><i class="fa-brands fa-vk fa-2xl"></i></a>
                    <p class="footer-text">
                        Наши соц.сети
                    </p>
                </div>
            </div>
        </div>
        <div class="line"></div>
        <div class="footer-subtitle">
            Copyright © 2024 The IGNIS. All Rights Reserved.
        </div>
    </footer>
</body>
</html>