carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('woman/', views.catalogWoman, name='catalog-woman'),
    path('woman/<slug:category_slug>/', views.catalogWoman, name='catalog-woman-category'),
    path('men/', views.catalogMen, name='catalog-men'),
    path('men/<slug:category_slug>/', views.catalogMen, name='catalog-men-category'),
    path('product/', views.product, name='product'),
    path('product/<int:product_id>', views.product, name='product'),
]

ignis_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from ignis_app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('catalog/', include('goods.urls', namespace = 'catalog-men')),
    path('catalog/', include('goods.urls', namespace = 'catalog-woman')),
    path('user/', include('users.urls', namespace = 'user')),
    path('cart/', include('carts.urls', namespace = 'cart')),
]

if settings.DEBUG:
    # urlpatterns = [
    #     path("__debug__/", include("debug_toolbar.urls")),
    # ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('', views.logout, name='logout'),
]

goods/models.py
from os import name
from tabnanny import verbose
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'
    
    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to="goods_images", blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')
    color = models.TextField(blank=True, null=True, verbose_name='Цвет')
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    size = models.PositiveIntegerField(default=0, blank=True, null=True, verbose_name='Размер')
    compound = models.TextField(blank=True, null=True, verbose_name='Состав')
    gender = models.TextField(blank=True, null=True, verbose_name='Пол')
    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    
    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'

    def display_id(self):
        return f'{self.id:05}'

goods/views.py
from django.shortcuts import render, get_object_or_404
from goods.models import Categories, Products

def catalogWoman(request, category_slug=None):
    categories = Categories.objects.all()
    goods = Products.objects.filter(gender="Жен")
    if category_slug:
        category = get_object_or_404(Categories, slug=category_slug)
        goods = goods.filter(category=category)
    context = {
        'title': 'IGNIS - Женский каталог',
        'year': '2024',
        'categories': categories,
        'goods': goods,
        'gender': "Женщинам",
        'gender_url': 'goods:catalog-woman'
    }
    return render(request, 'goods/catalog-woman.html', context)

def catalogMen(request, category_slug=None):
    categories = Categories.objects.all()
    goods = Products.objects.filter(gender="Муж")
    if category_slug:
        category = get_object_or_404(Categories, slug=category_slug)
        goods = goods.filter(category=category)
    context = {
        'title': 'IGNIS - Мужской каталог',
        'year': '2024',
        'categories': categories,
        'goods': goods,
        'gender': "Мужчинам",
        'gender_url': 'goods:catalog-man'
    }
    return render(request, 'goods/catalog-men.html', context)

def product(request, product_id):
    product = get_object_or_404(Products, id=product_id)
    gender_text = 'Женщинам' if product.gender == 'Жен' else 'Мужчинам'
    context = {
        'title': 'IGNIS - Продукт',
        'year': '2024',
        'product': product,
        'gender': gender_text
    }
    return render(request, 'goods/product.html', context)

goods/templates/goods/catalog-men.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static "deps/css/style.css" %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{% static "deps/css/normalize.css" %}">
	<link rel="icon" href="{% static "deps/media/favicon.ico" %}"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
</head>
<body>
	<header class="header">
		<div class="container">
			<div class="header-flex">
				<nav class="header-menu-left">
					<ul class="header-menu-list">
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-woman" %}"><i class="fa-solid fa-venus"></i> Женщинам</a></li>
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-men" %}"><i class="fa-solid fa-mars"></i> Мужчинам</a></li>
					</ul>
				</nav>
				<div class="header-logo">
					<a href="{% url "main:index" %}"><img src="{% static "deps/media/main/header/Logo.svg" %}" alt="" class="header-avatar"></a>
					<div class="header-line">
						<img src="{% static "deps/media/main/header/Line 1.svg" %}" alt="">
					</div>
					<h1 class="header-title">
						<a class="header-title-link" href="{% url "main:index" %}">ignis</a>
					</h1>
				</div>
				<nav class="header-menu-right">
					<ul class="header-menu-list">
						{% if not user.is_authenticated %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:login" %}"><i class="fa-solid fa-right-to-bracket"></i> Войти</a></li>
						{% else %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:profile" %}"><i class="fa-solid fa-user"></i> Профиль</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="favorites.html"><i class="fa-solid fa-heart"></i> Избранное</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "cart:cart_detail" %}"><i class="fa-solid fa-cart-shopping"></i> корзина</a></li>
							{% if user.is_admin or user.is_staff%}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "admin:index" %}"><i class="fa-solid"></i> админ панель</a></li>
							{% endif %}
						{% endif %}
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<main>
		<section class="catalog-men">
			<div class="container">
				<div class="catalog-men-flex">
					<div class="col-3">
						<nav class="catalog-men-navbar">
							<ul class="catalog-men-list">
								<li class="catalog-men-item"><a href="{% url "main:index" %}" class="catalog-men-link">Главная</a></li>
								<i class="fa-solid fa-chevron-right"></i>
								<li class="catalog-men-item"><a href="{% url "goods:catalog-woman" %}" class="catalog-men-link">Каталог</a></li>
								<i class="fa-solid fa-chevron-right"></i>
								<a href="{% if product.gender == 'Жен' %}{% url 'goods:catalog-woman' %}{% else %}{% url 'goods:catalog-men' %}{% endif %}" class="catalog-men-link">{{ gender }}</a>
							</ul>
						</nav>
						<div class="catalog-men-menu-items">
							<ul class="catalog-men-menu-list">
								{% for category in categories %}
								<li class="catalog-men-menu-item">
									<a href="{% url 'goods:catalog-men-category' category.slug %}" class="catalog-men-menu-link">{{category.name}}</a>
								</li>
								{% endfor %}	
							</ul>
						</div>
					</div>
					<div class="col-9">
						<nav class="catalog-men-navbar">
							<ul class="catalog-men-list">
								<li class="catalog-men-item"><a href="" class="catalog-men-link">Цвет</a><a href="" class="catalog-men-link"><i class="fa-solid fa-chevron-down"></i></a></li>
								<li class="catalog-men-item"><a href="" class="catalog-men-link">Цена</a><a href="" class="catalog-men-link"><i class="fa-solid fa-chevron-down"></i></a></li>
								<li class="catalog-men-item"><a href="" class="catalog-men-link">Размер</a><a href="" class="catalog-men-link"><i class="fa-solid fa-chevron-down"></i></a></li>
								<li class="catalog-men-item"><a href="" class="catalog-men-link">Сортировка</a><a href="" class="catalog-men-link"><i class="fa-solid fa-chevron-down"></i></a></li>
							</ul>
						</nav>
						<div class="catalog-men-flex">
                            {% for product in goods %}
								<div class="catalog-men-info">
									<div class="catalog-men-images">
										<a href="{% url 'goods:product' product.id %}">
											<img src="{{ product.image.url }}" alt="{{ product.name }}" class="catalog-men-avatar">
										</a>
										<a href="#"><i class="fa-regular fa-heart" style="color: #ffffff;"></i></a>
										<h2 class="catalog-men-text">
											<a class="catalog-men-title-link" href="{% url 'goods:product' product.id %}">{{ product.name }}</a>
										</h2>
										<p class="catalog-men-num">
											{{ product.price }} руб.
										</p>
										<div class="catalog-men-svg">
											<a href="#"><img src="{% static "deps/media/color_eclipse/Ellipse 1.svg" %}" alt="Color:white"></a>
											<a href="#"><img src="{% static "deps/media/color_eclipse/Ellipse 2.svg" %}" alt="Color:blue"></a>
											<a href="#"><img src="{% static "deps/media/color_eclipse/Ellipse 3.svg" %}" alt="Color:beige"></a>
										</div>
									</div>
								</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</section>
	</main>
	<footer class="footer">
		<div class="container">
			<div class="footer-flex">
				<div class="footer-number">
					<a href="">
						<i class="fa-solid fa-phone fa-2xl"></i>
						<p class="footer-text">
							+7 (999) 999 99-99
						</p>
					</a>
				</div>
				<div class="footer-adress">
					<a href=""><i class="fa-solid fa-location-dot fa-2xl"></i></a>
					<p class="footer-text">
						<a class="footer-map" href="https://maps.app.goo.gl/uRuEgu8wuG3qbstY8">г. Брянск, пр-т Станке Димитрова, д. 3 </a>
					</p>
				</div>
				<div class="footer-mail">
					<a href=""><i class="fa-solid fa-envelope fa-2xl"></i></a>
					<p class="footer-text">
						<a href="">ignis@gmail.com</a>
					</p>
				</div>
				<div class="footer-schedule">
					<i class="fa-solid fa-calendar fa-2xl"></i>
					<p class="footer-text">
						с 08:00 <br> до 22:00 по МСК
					</p>
				</div>
				<div class="footer-social">
					<a class="footer-link-social" href=""><i class="fa-brands fa-telegram fa-2xl"></i></a>
					<a class="footer-link-social" href=""><i class="fa-brands fa-vk fa-2xl"></i></a>
					<p class="footer-text">
						Наши соц.сети
					</p>
				</div>
			</div>
			<div class="line">
	
			</div>
			<div class="footer-subtitle">
				Copyright © {{ year }} The IGNIS. All Rights Reserved.
			</div>
		</div>
	</footer>
</body>
</html>

goods/templates/goods/catalog-woman.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static 'deps/css/style.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{% static 'deps/css/normalize.css' %}">
	<link rel="icon" href="{% static 'deps/media/favicon.ico' %}"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
</head>
<body>
	<header class="header">
		<div class="container">
			<div class="header-flex">
				<nav class="header-menu-left">
					<ul class="header-menu-list">
						<li class="header-menu-item"><a class="header-menu-link" href="{% url 'goods:catalog-woman' %}"><i class="fa-solid fa-venus"></i> Женщинам</a></li>
						<li class="header-menu-item"><a class="header-menu-link" href="{% url 'goods:catalog-men' %}"><i class="fa-solid fa-mars"></i> Мужчинам</a></li>
					</ul>
				</nav>
				<div class="header-logo">
					<a href="{% url 'main:index' %}"><img src="{% static 'deps/media/main/header/Logo.svg' %}" alt="" class="header-avatar"></a>
					<div class="header-line">
						<img src="{% static 'deps/media/main/header/Line 1.svg' %}" alt="">
					</div>
					<h1 class="header-title">
						<a class="header-title-link" href="{% url 'main:index' %}">ignis</a>
					</h1>
				</div>
				<nav class="header-menu-right">
					<ul class="header-menu-list">
						{% if not user.is_authenticated %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:login" %}"><i class="fa-solid fa-right-to-bracket"></i> Войти</a></li>
						{% else %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:profile" %}"><i class="fa-solid fa-user"></i> Профиль</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="favorites.html"><i class="fa-solid fa-heart"></i> Избранное</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "cart:cart_detail" %}"><i class="fa-solid fa-cart-shopping"></i> корзина</a></li>
							{% if user.is_admin or user.is_staff%}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "admin:index" %}"><i class="fa-solid"></i> админ панель</a></li>
							{% endif %}
						{% endif %}
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<main>
		<section class="catalog-woman">
			<div class="container">
				<div class="catalog-woman-flex">
					<div class="col-3">
						<nav class="catalog-woman-navbar">
							<ul class="catalog-woman-list">
								<li class="catalog-woman-item"><a href="{% url 'main:index' %}" class="catalog-woman-link">Главная</a></li>
								<i class="fa-solid fa-chevron-right"></i>
								<li class="catalog-woman-item"><a href="{% url 'goods:catalog-woman' %}" class="catalog-woman-link">Каталог</a></li>
								<i class="fa-solid fa-chevron-right"></i>
								<a href="{% if product.gender == 'Жен' %}{% url 'goods:catalog-woman' %}{% else %}{% url 'goods:catalog-men' %}{% endif %}" class="catalog-woman-link">{{ gender }}</a>
							</ul>
						</nav>
						<div class="catalog-woman-menu-items">
							<ul class="catalog-woman-menu-list">
								{% for category in categories %}
									<li class="catalog-woman-menu-item">
										<a href="{% url 'goods:catalog-woman-category' category.slug %}" class="catalog-woman-menu-link">{{ category.name }}</a>
									</li>
								{% endfor %}
							</ul>
						</div>
					</div>
					<div class="col-9">
						<nav class="catalog-woman-navbar">
							<ul class="catalog-woman-list">
								<li class="catalog-woman-item"><a href="" class="catalog-woman-link">Цвет</a><a href="" class="catalog-woman-link"><i class="fa-solid fa-chevron-down"></i></a></li>
								<li class="catalog-woman-item"><a href="" class="catalog-woman-link">Цена</a><a href="" class="catalog-woman-link"><i class="fa-solid fa-chevron-down"></i></a></li>
								<li class="catalog-woman-item"><a href="" class="catalog-woman-link">Размер</a><a href="" class="catalog-woman-link"><i class="fa-solid fa-chevron-down"></i></a></li>
								<li class="catalog-woman-item"><a href="" class="catalog-woman-link">Сортировка</a><a href="" class="catalog-woman-link"><i class="fa-solid fa-chevron-down"></i></a></li>
							</ul>
						</nav>
						<div class="catalog-woman-flex">
							{% for product in goods %}
								<div class="catalog-woman-info">
									<div class="catalog-woman-images">
										<a href="{% url 'goods:product' product.id %}">
											<img src="{{ product.image.url }}" alt="{{ product.name }}" class="catalog-woman-avatar">
										</a>
										<a href="#"><i class="fa-regular fa-heart" style="color: #ffffff;"></i></a>
										<h2 class="catalog-woman-text">
											<a class="catalog-woman-title-link" href="{% url 'goods:product' product.id %}">{{ product.name }}</a>
										</h2>
										<p class="catalog-woman-num">
											{{ product.price }} руб.
										</p>
										<div class="catalog-woman-svg">
											<a href="#"><img src="{% static "deps/media/color_eclipse/Ellipse 1.svg" %}" alt="Color:white"></a>
											<a href="#"><img src="{% static "deps/media/color_eclipse/Ellipse 2.svg" %}" alt="Color:blue"></a>
											<a href="#"><img src="{% static "deps/media/color_eclipse/Ellipse 3.svg" %}" alt="Color:beige"></a>
										</div>
									</div>
								</div>
							{% endfor %}
						</div>				
					</div>
				</div>
			</div>
		</section>
	</main>
	<footer class="footer">
		<div class="container">
			<div class="footer-flex">
				<div class="footer-number">
					<a href="">
						<i class="fa-solid fa-phone fa-2xl"></i>
						<p class="footer-text">
							+7 (999) 999 99-99
						</p>
					</a>
				</div>
				<div class="footer-adress">
					<a href=""><i class="fa-solid fa-location-dot fa-2xl"></i></a>
					<p class="footer-text">
						<a class="footer-map" href="https://maps.app.goo.gl/uRuEgu8wuG3qbstY8">г. Брянск, пр-т Станке Димитрова, д. 3 </a>
					</p>
				</div>
				<div class="footer-mail">
					<a href=""><i class="fa-solid fa-envelope fa-2xl"></i></a>
					<p class="footer-text">
						<a href="">ignis@gmail.com</a>
					</p>
				</div>
				<div class="footer-schedule">
					<i class="fa-solid fa-calendar fa-2xl"></i>
					<p class="footer-text">
						с 08:00 <br> до 22:00 по МСК
					</p>
				</div>
				<div class="footer-social">
					<a class="footer-link-social" href=""><i class="fa-brands fa-telegram fa-2xl"></i></a>
					<a class="footer-link-social" href=""><i class="fa-brands fa-vk fa-2xl"></i></a>
					<p class="footer-text">
						Наши соц.сети
					</p>
				</div>
			</div>
			<div class="line">
	
			</div>
			<div class="footer-subtitle">
				Copyright © {{ year }} The IGNIS. All Rights Reserved.
			</div>
		</div>
	</footer>
</body>
</html>

goods/templates/goods/product.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static "deps/css/style.css" %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{% static "deps/css/normalize.css" %}">
	<link rel="icon" href="{% static "deps/media/favicon.ico" %}"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
</head>
<body>
	<header class="header">
		<div class="container">
			<div class="header-flex">
				<nav class="header-menu-left">
					<ul class="header-menu-list">
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-woman" %}"><i class="fa-solid fa-venus"></i> Женщинам</a></li>
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-men" %}"><i class="fa-solid fa-mars"></i> Мужчинам</a></li>
					</ul>
				</nav>
				<div class="header-logo">
					<a href="{% url "main:index" %}"><img src="{% static "deps/media/main/header/Logo.svg" %}" alt="" class="header-avatar"></a>
					<div class="header-line">
						<img src="{% static "deps/media/main/header/Line 1.svg" %}" alt="">
					</div>
					<h1 class="header-title">
						<a class="header-title-link" href="{% url "main:index" %}">ignis</a>
					</h1>
				</div>
				<nav class="header-menu-right">
					<ul class="header-menu-list">
						{% if not user.is_authenticated %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:login" %}"><i class="fa-solid fa-right-to-bracket"></i> Войти</a></li>
						{% else %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:profile" %}"><i class="fa-solid fa-user"></i> Профиль</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="favorites.html"><i class="fa-solid fa-heart"></i> Избранное</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "cart:cart_detail" %}"><i class="fa-solid fa-cart-shopping"></i> корзина</a></li>
							{% if user.is_admin or user.is_staff%}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "admin:index" %}"><i class="fa-solid"></i> админ панель</a></li>
							{% endif %}
						{% endif %}
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<main>
		<section class="product">
			<div class="container">
				<nav class="product-navbar">
					<ul class="product-list">
						<li class="catalog-woman-item"><a href="{% url 'main:index' %}" class="catalog-woman-link">Главная</a></li>
						<i class="fa-solid fa-chevron-right"></i>
						<li class="catalog-woman-item"><a href="{% url 'goods:catalog-woman' %}" class="catalog-woman-link">Каталог</a></li>
						<i class="fa-solid fa-chevron-right"></i>
						<li class="catalog-woman-item">
							<a href="{% if product.gender == 'Жен' %}{% url 'goods:catalog-woman' %}{% else %}{% url 'goods:catalog-men' %}{% endif %}" class="catalog-woman-link">{{ gender }}</a>
						</li>						
						<i class="fa-solid fa-chevron-right"></i>
						<li class="product-item"><a href="" class="product-link">{{ product.name }}</a></li>
					</ul>
				</nav>
				<div class="product-info">
					<div class="product-flex">
						<div class="product-images">
							<div class="product-img">
								<img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-avatar">
							</div>
						</div>
						<div class="product-main-img">
							<img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-main-avatar">
						</div>
						<div class="product-main-info">
							<p class="product-main-text">{{ product.name }}</p>
							<p class="product-main-price">{{ product.price }} руб</p>
							<div class="product-main-icon">
								<a href="#"><img src="{% static 'deps/media/color_eclipse/Ellipse 1.svg' %}" alt="Color:white"></a>
								<a href="#"><img src="{% static 'deps/media/color_eclipse/Ellipse 2.svg' %}" alt="Color:blue"></a>
								<a href="#"><img src="{% static 'deps/media/color_eclipse/Ellipse 3.svg' %}" alt="Color:beige"></a>
							</div>
							<p class="product-main-name">В наличии: {{ product.quantity }}</p>
							<p class="product-main-name">Цвет: {{ product.color }}</p>
							<p class="product-main-name">Артикул: {{ product.display_id }}</p>
							<p class="product-main-name">Выберите размер:</p>
							<div class="product-main-flex-3">
								{{product.size}}
							</div>
							<div class="product-main-button">
								<button class="product-button">В КОРЗИНУ</button>
								<button class="product-button"><i class="fa-regular fa-heart"></i> В ИЗБРАННОЕ</button>
							</div>
							<a class="product-main-title-information">Подробности:</a>
							<div class="product-main-flex">
								<p class="product-main-information">{{ product.description }}</p>
							</div>
							<div class="product-main-flex-2">
								<p class="product-main-title-information">Состав:</p>
							</div>
							<div class="prd-main">
								<p class="product-main-slogan">{{ product.compound }}</p>
							</div>
							<div class="product-line">
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</main>
	
	<footer class="footer">
		<div class="container">
			<div class="footer-flex">
				<div class="footer-number">
					<a href="">
						<i class="fa-solid fa-phone fa-2xl"></i>
						<p class="footer-text">
							+7 (999) 999 99-99
						</p>
					</a>
				</div>
				<div class="footer-adress">
					<a href=""><i class="fa-solid fa-location-dot fa-2xl"></i></a>
					<p class="footer-text">
						<a class="footer-map" href="https://maps.app.goo.gl/uRuEgu8wuG3qbstY8">г. Брянск, пр-т Станке Димитрова, д. 3 </a>
					</p>
				</div>
				<div class="footer-mail">
					<a href=""><i class="fa-solid fa-envelope fa-2xl"></i></a>
					<p class="footer-text">
						<a href="">ignis@gmail.com</a>
					</p>
				</div>
				<div class="footer-schedule">
					<i class="fa-solid fa-calendar fa-2xl"></i>
					<p class="footer-text">
						с 08:00 <br> до 22:00 по МСК
					</p>
				</div>
				<div class="footer-social">
					<a class="footer-link-social" href=""><i class="fa-brands fa-telegram fa-2xl"></i></a>
					<a class="footer-link-social" href=""><i class="fa-brands fa-vk fa-2xl"></i></a>
					<p class="footer-text">
						Наши соц.сети
					</p>
				</div>
			</div>
			<div class="line">
	
			</div>
			<div class="footer-subtitle">
				Copyright © {{ year }} The IGNIS. All Rights Reserved.
			</div>
		</div>
	</footer>
</body>
</html>