carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('woman/', views.catalogWoman, name='catalog-woman'),
    path('woman/<slug:category_slug>/', views.catalogWoman, name='catalog-woman-category'),
    path('men/', views.catalogMen, name='catalog-men'),
    path('men/<slug:category_slug>/', views.catalogMen, name='catalog-men-category'),
    path('product/', views.product, name='product'),
    path('product/<int:product_id>', views.product, name='product'),
]

ignis_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from ignis_app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('catalog/', include('goods.urls', namespace = 'catalog-men')),
    path('catalog/', include('goods.urls', namespace = 'catalog-woman')),
    path('user/', include('users.urls', namespace = 'user')),
    path('cart/', include('carts.urls', namespace = 'cart')),
]

if settings.DEBUG:
    # urlpatterns = [
    #     path("__debug__/", include("debug_toolbar.urls")),
    # ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('', views.logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    phone_number = models.CharField(max_length=11, blank=True, null=True, verbose_name='Номер телефона')
    town = models.CharField(max_length=50, blank=True, null=True, verbose_name='Город')
    street = models.CharField(max_length=50, blank=True, null=True, verbose_name='Улица')
    house = models.CharField(max_length=50, blank=True, null=True, verbose_name='Дом')
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User

class UserLoginForm(AuthenticationForm):
    pass
    class Meta:
        model = User
        fields = ['username', 'password',]


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "username",
            "phone_number",
            "password1",
            "password2",
        )
    
    username = forms.CharField()
    phone_number = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
            "town",
            "street",
            "house",)

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    phone_number = forms.CharField()
    town = forms.CharField()
    street = forms.CharField()
    house = forms.CharField()

users/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return redirect(reverse('main:index'))
            else:
                form.add_error(None, 'Неправильное имя пользователя или пароль')
    else:
        form = UserLoginForm()
    
    context = {
        'title': 'IGNIS - Авторизация',
        'form': form,
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    
    context = {
        'title': 'IGNIS - Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)



def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    context = {
        'title': 'IGNIS - Личный кабинет',
        'form': form
    }
    return render(request, 'users/profile.html', context)

def logout(request):
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static "deps/css/style.css" %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{% static "deps/css/normalize.css" %}">
	<link rel="icon" href="{% static "deps/media/favicon.ico" %}"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
</head>
<body>
	<header class="header">
		<div class="container">
			<div class="header-flex">
				<nav class="header-menu-left">
					<ul class="header-menu-list">
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-woman" %}"><i class="fa-solid fa-venus"></i> Женщинам</a></li>
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-men" %}"><i class="fa-solid fa-mars"></i> Мужчинам</a></li>
					</ul>
				</nav>
				<div class="header-logo">
					<a href="{% url "main:index" %}"><img src="{% static "deps/media/main/header/Logo.svg" %}" alt="" class="header-avatar"></a>
					<div class="header-line">
						<img src="{% static "deps/media/main/header/Line 1.svg" %}" alt="">
					</div>
					<h1 class="header-title">
						<a class="header-title-link" href="{% url "main:index" %}">ignis</a>
					</h1>
				</div>
				<nav class="header-menu-right">
					<ul class="header-menu-list">
						{% if not user.is_authenticated %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:login" %}"><i class="fa-solid fa-right-to-bracket"></i> Войти</a></li>
						{% endif %}
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<main>
		<section class="login">
			<div class="login-flex">
				<form action="{% url 'user:login' %}" method="post" class="login-form">
					{% csrf_token %}
					<h1 class="login-title">Авторизация</h1>
					
					{% if form.non_field_errors %}
						<div class="alert">
							{% for error in form.non_field_errors %}
								<p>{{ error }}</p>
							{% endfor %}
						</div>
					{% endif %}
					
					<div class="login-email">
						<label for="id_username"></label>
						<input type="text" name="username" id="id_username" 
							   value="{{ form.username.value|default_if_none:'' }}" 
							   placeholder="Введите имя пользователя" required>
						{% for error in form.username.errors %}
							<div class="alert">
								<p>{{ error }}</p>
							</div>
						{% endfor %}
					</div>
					
					<div class="login-password">
						<input type="password" name="password" id="id_password" 
							   placeholder="Введите пароль" required>
						{% for error in form.password.errors %}
							<div class="alert">
								<p>{{ error }}</p>
							</div>
						{% endfor %}
						{% comment %} <a href="#"><i class="fa-solid fa-eye fa-xl"></i></a> {% endcomment %}
					</div>
					
					<div class="login-remember">
						<label>
							<input type="checkbox" name="remember_me" id="remember_me"> Запомнить пароль
						</label>
						<a href="#">Забыли пароль?</a>
					</div> 
					
					<button type="submit" class="login-button button">Войти</button> 
					
					<div class="login-link">
						<p class="login-text">
							<a href="{% url 'users:registration' %}">Зарегистрироваться</a>
						</p>
					</div> 
				</form>
				
			</div>
		</section>
	</main>
	<footer class="footer">
		<div class="container">
			<div class="footer-flex">
				<div class="footer-number">
					<a href="">
						<i class="fa-solid fa-phone fa-2xl"></i>
						<p class="footer-text">
							+7 (999) 999 99-99
						</p>
					</a>
				</div>
				<div class="footer-adress">
					<a href=""><i class="fa-solid fa-location-dot fa-2xl"></i></a>
					<p class="footer-text">
						<a class="footer-map" href="https://maps.app.goo.gl/uRuEgu8wuG3qbstY8">г. Брянск, пр-т Станке Димитрова, д. 3 </a>
					</p>
				</div>
				<div class="footer-mail">
					<a href=""><i class="fa-solid fa-envelope fa-2xl"></i></a>
					<p class="footer-text">
						<a href="">ignis@gmail.com</a>
					</p>
				</div>
				<div class="footer-schedule">
					<i class="fa-solid fa-calendar fa-2xl"></i>
					<p class="footer-text">
						с 08:00 <br> до 22:00 по МСК
					</p>
				</div>
				<div class="footer-social">
					<a class="footer-link-social" href=""><i class="fa-brands fa-telegram fa-2xl"></i></a>
					<a class="footer-link-social" href=""><i class="fa-brands fa-vk fa-2xl"></i></a>
					<p class="footer-text">
						Наши соц.сети
					</p>
				</div>
			</div>
			<div class="line">
	
			</div>
			<div class="footer-subtitle">
				Copyright © {{ year }} The IGNIS. All Rights Reserved.
			</div>
		</div>
	</footer>
</body>
</html>

users/templates/users/profile.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static "deps/css/style.css" %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{% static "deps/css/normalize.css" %}">
	<link rel="icon" href="{% static "deps/media/favicon.ico" %}"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
</head>
<body>
	<header class="header">
		<div class="container">
			<div class="header-flex">
				<nav class="header-menu-left">
					<ul class="header-menu-list">
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-woman" %}"><i class="fa-solid fa-venus"></i> Женщинам</a></li>
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-men" %}"><i class="fa-solid fa-mars"></i> Мужчинам</a></li>
					</ul>
				</nav>
				<div class="header-logo">
					<a href="{% url "main:index" %}"><img src="{% static "deps/media/main/header/Logo.svg" %}" alt="" class="header-avatar"></a>
					<div class="header-line">
						<img src="{% static "deps/media/main/header/Line 1.svg" %}" alt="">
					</div>
					<h1 class="header-title">
						<a class="header-title-link" href="{% url "main:index" %}">ignis</a>
					</h1>
				</div>
				<nav class="header-menu-right">
					<ul class="header-menu-list">
						{% if not user.is_authenticated %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:login" %}"><i class="fa-solid fa-right-to-bracket"></i> Войти</a></li>
						{% else %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:profile" %}"><i class="fa-solid fa-user"></i> Профиль</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="favorites.html"><i class="fa-solid fa-heart"></i> Избранное</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "cart:cart_detail" %}"><i class="fa-solid fa-cart-shopping"></i> корзина</a></li>
							{% if user.is_admin or user.is_staff%}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "admin:index" %}"><i class="fa-solid"></i> админ панель</a></li>
							{% endif %}
						{% endif %}
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<main>
		<section class="profile">
			<div class="container-small">
				<div class="profile-menu">
					<ul class="profile-menu-list">
						<li class="profile-item"><a class="profile-menu-link" href="{% url "main:index" %}">Главная</a></li>
						<i class="fa-solid fa-chevron-right"></i>
						<li class="profile-item"><a class="profile-menu-link" href="{% url "user:profile" %}">Личный кабинет</a></li>
					</ul>
				</div>
				<div class="profile-menu-history">
					<ul class="profile-menu-list">
						<li class="profile-menu-item"><a href="#">История заказов</a></li>
						<li class="profile-menu-item"><a href="{% url "user:profile" %}">Личный кабинет</a></li>
						<li class="profile-menu-item"><a href="{% url "user:logout" %}">Выйти</a></li>
					</ul>
				</div>
				<div class="profile-personal-info">
					<h1 class="profile-info-title">
						Персональные данные:
					</h1>
					<form action="{% url 'user:profile' %}" method="POST" class="profile-form">
						{% csrf_token %}
						<div class="profile-item">
							<input type="text" id="id_first_name" name="first_name" value="{{ form.first_name.value|default_if_none:'' }}" placeholder="Имя" required>
							{% for error in form.first_name.errors %}
							<div class="alert">
								<p>{{ error }}</p>
							</div>
							{% endfor %}
							<input type="text" id="id_last_name" name="last_name" value="{{ form.last_name.value|default_if_none:'' }}" placeholder="Фамилия">
							{% for error in form.last_name.errors %}
							<div class="alert">
								<p>{{ error }}</p>
							</div>
							{% endfor %}
							<input type="text" id="id_username" name="username" value="{{ form.username.value|default_if_none:'' }}" placeholder="Имя пользователя">
							{% for error in form.username.errors %}
							<div class="alert">
								<p>{{ error }}</p>
							</div>
							{% endfor %}
						</div>
						<div class="profile-item profile-item-second">
							<input type="email" id="id_email" name="email" value="{{ form.email.value|default_if_none:'' }}" placeholder="E-mail" required>
							{% for error in form.email.errors %}
							<div class="alert">
								<p>{{ error }}</p>
							</div>
							{% endfor %}
							<input type="phone" id="id_phone_number" name="phone_number" value="{{ form.phone_number.value|default_if_none:'' }}" placeholder="Телефон" required>
							{% for error in form.phone_number.errors %}
							<div class="alert">
								<p>{{ error }}</p>
							</div>
							{% endfor %}
						</div>
						<div class="profile-personal-info">
							<h1 class="profile-info-title">
								Адрес доставки:
							</h1>
							<div class="profile-item">
								<input type="text" id="id_town" name="town" value="{{ form.town.value|default_if_none:'' }}" placeholder="Город" required>
								<input type="text" id="id_street" name="street" value="{{ form.street.value|default_if_none:'' }}" placeholder="Улица" required>
								<input type="text" id="id_house" name="house" value="{{ form.house.value|default_if_none:'' }}" placeholder="Дом" required>
							</div>
							<button type="submit" class="profile-button">
								ОБНОВИТЬ ИНФОРМАЦИЮ
							</button>
							<p class"profile-approval">Заполняя данную форму Вы даёте согласие на обработку персональных данных</p>
						</div>
					</form>
				</div>		
			</div>
		</section>
	</main>
	<footer class="footer">
		<div class="container">
			<div class="footer-flex">
				<div class="footer-number">
					<a href="">
						<i class="fa-solid fa-phone fa-2xl"></i>
						<p class="footer-text">
							+7 (999) 999 99-99
						</p>
					</a>
				</div>
				<div class="footer-adress">
					<a href=""><i class="fa-solid fa-location-dot fa-2xl"></i></a>
					<p class="footer-text">
						<a class="footer-map" href="https://maps.app.goo.gl/uRuEgu8wuG3qbstY8">г. Брянск, пр-т Станке Димитрова, д. 3 </a>
					</p>
				</div>
				<div class="footer-mail">
					<a href=""><i class="fa-solid fa-envelope fa-2xl"></i></a>
					<p class="footer-text">
						<a href="">ignis@gmail.com</a>
					</p>
				</div>
				<div class="footer-schedule">
					<i class="fa-solid fa-calendar fa-2xl"></i>
					<p class="footer-text">
						с 08:00 <br> до 22:00 по МСК
					</p>
				</div>
				<div class="footer-social">
					<a class="footer-link-social" href=""><i class="fa-brands fa-telegram fa-2xl"></i></a>
					<a class="footer-link-social" href=""><i class="fa-brands fa-vk fa-2xl"></i></a>
					<p class="footer-text">
						Наши соц.сети
					</p>
				</div>
			</div>
			<div class="line">
	
			</div>
			<div class="footer-subtitle">
				Copyright © {{ year }} The IGNIS. All Rights Reserved.
			</div>
		</div>
	</footer>
</body>
</html>

users/templates/users/registration.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static "deps/css/style.css" %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{% static "deps/css/normalize.css" %}">
	<link rel="icon" href="{% static "deps/media/favicon.ico" %}"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
</head>
<body>
	<header class="header">
		<div class="container">
			<div class="header-flex">
				<nav class="header-menu-left">
					<ul class="header-menu-list">
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-woman" %}"><i class="fa-solid fa-venus"></i> Женщинам</a></li>
						<li class="header-menu-item"><a class="header-menu-link" href="{% url "goods:catalog-men" %}"><i class="fa-solid fa-mars"></i> Мужчинам</a></li>
					</ul>
				</nav>
				<div class="header-logo">
					<a href="{% url "main:index" %}"><img src="{% static "deps/media/main/header/Logo.svg" %}" alt="" class="header-avatar"></a>
					<div class="header-line">
						<img src="{% static "deps/media/main/header/Line 1.svg" %}" alt="">
					</div>
					<h1 class="header-title">
						<a class="header-title-link" href="{% url "main:index" %}">ignis</a>
					</h1>
				</div>
				<nav class="header-menu-right">
					<ul class="header-menu-list">
						{% if not user.is_authenticated %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:login" %}"><i class="fa-solid fa-right-to-bracket"></i> Войти</a></li>
						{% else %}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "users:profile" %}"><i class="fa-solid fa-user"></i> Профиль</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="favorites.html"><i class="fa-solid fa-heart"></i> Избранное</a></li>
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "cart:cart_detail" %}"><i class="fa-solid fa-cart-shopping"></i> корзина</a></li>
							{% if user.is_admin or user.is_staff%}
							<li class="header-menu-item"><a class="header-menu-link" href="{% url "admin:index" %}"><i class="fa-solid"></i> админ панель</a></li>
							{% endif %}
						{% endif %}
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<main>
		<section class="registr">
			<div class="registr-flex">
				<form action="{% url 'user:registration' %}" method="POST" class="registr-form">
					{% csrf_token %}
					<h1 class="registr-title">Регистрация</h1>
					<div class="registr-email">
						<label for="id_username"></label>
						<input type="text" id="id_username" name="username" 
							   value="{{ form.username.value|default_if_none:'' }}" 
							   placeholder="Имя пользователя" required>
					</div>
					{% for error in form.username.errors %}
					<div class="alert">
						<p>{{ error }}</p>
					</div>
					{% endfor %}
					<div class="registr-email">
						<label for="id_phone_number"></label>
						<input type="tel" id="id_phone_number" name="phone_number"
							   value="{{ form.phone_number.value|default_if_none:'' }}" 
							   placeholder="Номер телефона" required>
					</div>
					{% for error in form.phone_number.errors %}
					<div class="alert">
						<p>{{ error }}</p>
					</div>
					{% endfor %}
					<div class="registr-email">
						<label for="id_password1"></label>
						<input type="password" id="id_password1" name="password1"
							   value="{{ form.password1.value|default_if_none:'' }}" 
							   placeholder="Пароль" required>
					</div>
					{% for error in form.password1.errors %}
					<div class="alert">
						<p>{{ error }}</p>
					</div>
					{% endfor %}
					<div class="registr-email">
						<label for="id_password2"></label>
						<input type="password" id="id_password2" name="password2"
							   value="{{ form.password2.value|default_if_none:'' }}" 
							   placeholder="Подтвердите пароль" required>
					</div>
					{% for error in form.password2.errors %}
					<div class="alert">
						<p>{{ error }}</p>
					</div>
					{% endfor %}
					<button type="submit" class="registr-button button">Зарегистрироваться</button>
				</form>
				
			</div>
		</section>
	</main>
	<footer class="footer">
		<div class="container">
			<div class="footer-flex">
				<div class="footer-number">
					<a href="">
						<i class="fa-solid fa-phone fa-2xl"></i>
						<p class="footer-text">
							+7 (999) 999 99-99
						</p>
					</a>
				</div>
				<div class="footer-adress">
					<a href=""><i class="fa-solid fa-location-dot fa-2xl"></i></a>
					<p class="footer-text">
						<a class="footer-map" href="https://maps.app.goo.gl/uRuEgu8wuG3qbstY8">г. Брянск, пр-т Станке Димитрова, д. 3 </a>
					</p>
				</div>
				<div class="footer-mail">
					<a href=""><i class="fa-solid fa-envelope fa-2xl"></i></a>
					<p class="footer-text">
						<a href="">ignis@gmail.com</a>
					</p>
				</div>
				<div class="footer-schedule">
					<i class="fa-solid fa-calendar fa-2xl"></i>
					<p class="footer-text">
						с 08:00 <br> до 22:00 по МСК
					</p>
				</div>
				<div class="footer-social">
					<a class="footer-link-social" href=""><i class="fa-brands fa-telegram fa-2xl"></i></a>
					<a class="footer-link-social" href=""><i class="fa-brands fa-vk fa-2xl"></i></a>
					<p class="footer-text">
						Наши соц.сети
					</p>
				</div>
			</div>
			<div class="line">
	
			</div>
			<div class="footer-subtitle">
				Copyright © {{ year }} The IGNIS. All Rights Reserved.
			</div>
		</div>
	</footer>
</body>
</html>